name:                monads
version:             0.1.0.0
github:              "celsobonutti/monads"
license:             BSD3
author:              "Celso Bonutti"
maintainer:          "i.am@cel.so"
copyright:           "Celso Bonutti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/celsobonutti/monads#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  generate-exposed-modules:
    - Paths_monads
  dependencies:
    - QuickCheck
    - checkers
executables:
  monads-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monads

tests:
  monads-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monads
    - QuickCheck
    - checkers
